#!/usr/bin/env perl

use strict;
use warnings FATAL => 'all';

use AdventOfCode::Day06 qw(part_1 part_2);
use AdventOfCode::Util 'slurp_input';

printf "Part 1 : %d\n", scalar @{part_1(slurp_input('./input-06.txt'))};
printf "Part 2 : %s\n", part_2(slurp_input('./input-06.txt'));
